"""Read every table with DuckDB and compare against Spark's measured answers.

Expected values come from truth.json, which build.py produced by running the
same SQL through Spark. Nothing in this file is a hardcoded constant from a
previous run, including the snapshot IDs used for time travel.
"""
import json
import os
import statistics
import sys
import time

import duckdb

from spark_setup import metadata_json, TRUTH_PATH, WAREHOUSE
import checks as C

PASS, FAIL, SKIP, GAP = "PASS", "FAIL", "n/a ", "GAP "
results = []


def record(label, status, detail=""):
    """GAP = a known, expected limitation -- reported, but not a suite failure."""
    results.append((label, status, detail))
    icon = {"PASS": "✓", "FAIL": "✗", SKIP: "-", GAP: "!"}[status]
    print(f"  {icon} {label:44} {status}  {detail}", flush=True)


def scan(table):
    return f"iceberg_scan('{metadata_json(table)}')"


def main():
    if not os.path.exists(TRUTH_PATH):
        print(f"missing {TRUTH_PATH} -- run: python bench/build.py", file=sys.stderr)
        return 2
    truth = json.load(open(TRUTH_PATH))

    con = duckdb.connect()
    con.execute("INSTALL iceberg; LOAD iceberg;")
    print(f"\nDuckDB {duckdb.__version__}  vs  Spark {truth['versions']['spark']} "
          f"+ Iceberg {truth['versions']['iceberg']}\n")

    print("READ CORRECTNESS (DuckDB result vs Spark result on identical SQL)")
    for key, table, label, sql in C.CHECKS:
        exp = [tuple(r) for r in truth["checks"][key]["rows"]]
        try:
            got = C.normalize_rows(con.execute(sql.format(t=scan(table))).fetchall())
        except Exception as e:
            record(label, FAIL, f"ERROR {type(e).__name__}: {str(e).splitlines()[0][:70]}")
            continue
        record(label, PASS if got == exp else FAIL,
               "" if got == exp else f"duckdb={got} spark={exp}")

    # Row lineage metadata columns
    exp = [tuple(r) for r in truth["lineage"]]
    try:
        got = C.normalize_rows(con.execute(
            C.LINEAGE_SQL.format(t=scan("f.lineage"), cols=", ".join(C.LINEAGE_COLS))
        ).fetchall())
        record("v3 row lineage (_row_id, _seq_number)", PASS if got == exp else FAIL,
               "" if got == exp else f"duckdb={got} spark={exp}")
    except Exception as e:
        record("v3 row lineage (_row_id, _seq_number)", FAIL,
               f"ERROR {str(e).splitlines()[0][:70]}")

    # Variant, compared as parsed JSON so key order and number formatting differences
    # between the two engines do not create false failures.
    exp = [[r[0], r[1]] for r in truth["variant"]]
    try:
        raw = con.execute(C.VARIANT_SQL_DUCKDB.format(t=scan(C.VARIANT_TABLE))).fetchall()
        got = [[r[0], C.normalize_json(r[1])] for r in raw]
        record("v3 variant type (deep/awkward values)", PASS if got == exp else FAIL,
               "" if got == exp else f"duckdb={got} spark={exp}")
        vtype = con.execute(f"SELECT typeof(v) FROM {scan(C.VARIANT_TABLE)} LIMIT 1").fetchone()[0]
        record("v3 variant exposed as native type", PASS if vtype.upper() == "VARIANT" else FAIL,
               f"typeof() = {vtype}")
    except Exception as e:
        record("v3 variant type (deep/awkward values)", FAIL,
               f"ERROR {str(e).splitlines()[0][:70]}")

    # Time travel: snapshot IDs come from truth.json, generated by this clone's build
    ok = 0
    for entry in truth["timetravel"]:
        sid, exp_n = entry["snapshot_id"], entry["count"]
        try:
            got_n = con.execute(
                f"SELECT count(*) FROM iceberg_scan('{metadata_json('h.part')}', "
                f"snapshot_from_id={sid})").fetchone()[0]
            ok += (got_n == exp_n)
        except Exception:
            pass
    record("v3 time travel across DV snapshots", PASS if ok == len(truth["timetravel"]) else FAIL,
           f"{ok}/{len(truth['timetravel'])} snapshots match")

    # ---- write side ----
    print("\nWRITE SUPPORT (DuckDB)")
    outdir = os.path.join(WAREHOUSE, "_duckdb_out")
    os.system(f"rm -rf '{outdir}'")
    try:
        con.execute(f"COPY (SELECT 1 a) TO '{outdir}' (FORMAT ICEBERG, FORMAT_VERSION 3)")
        import glob
        m = sorted(glob.glob(os.path.join(outdir, "metadata", "*.metadata.json")))
        fv = json.load(open(m[-1]))["format-version"] if m else "?"
        record("DuckDB writes Iceberg v3 on request", GAP if fv != 3 else PASS,
               f"asked for v3, got format-version={fv} (no error raised)")
    except Exception as e:
        record("DuckDB writes Iceberg v3 on request", GAP,
               f"{type(e).__name__}: {str(e).splitlines()[0][:70]}")

    # ---- features no available writer can produce ----
    print("\nUNTESTED (Spark could not write these, so DuckDB is not graded on them)")
    for feat, info in truth["unwritable"].items():
        if info["writable"]:
            record(f"{feat} (now writable!)", GAP,
                   "writer gained support -- add a DuckDB read check for this")
        else:
            record(feat, SKIP, (info["error"] or "")[:92])

    # ---- performance ----
    nrows = truth["versions"]["rows_perf_table"]
    print(f"\nREAD PERFORMANCE ({nrows:,}-row tables, same delete workload)")

    def bench(table, n=7):
        src = scan(table)
        con.execute(f"SELECT count(*) FROM {src}").fetchall()  # warm
        ts = []
        for _ in range(n):
            t0 = time.perf_counter()
            con.execute(f"SELECT count(*), sum(id) FROM {src}").fetchall()
            ts.append((time.perf_counter() - t0) * 1000)
        return statistics.median(ts)

    v3ms, v2ms = bench("p.big3"), bench("p.big2")
    lay = truth["layout"]
    print(f"  v3 deletion vectors (Puffin)   median {v3ms:7.1f} ms   "
          f"{lay['v3']['delete_artifacts']} delete artifacts, "
          f"{lay['v3']['delete_bytes']/1024:.1f} KiB")
    print(f"  v2 positional deletes          median {v2ms:7.1f} ms   "
          f"{lay['v2']['delete_artifacts']} delete artifacts, "
          f"{lay['v2']['delete_bytes']/1024:.1f} KiB")
    print(f"  -> v3 is {v2ms/v3ms:.1f}x faster on this machine")

    # ---- summary ----
    n_fail = sum(1 for _, s, _ in results if s == FAIL)
    n_pass = sum(1 for _, s, _ in results if s == PASS)
    n_skip = sum(1 for _, s, _ in results if s == SKIP)
    n_gap = sum(1 for _, s, _ in results if s == GAP)
    print(f"\n{n_pass} passed, {n_fail} failed, {n_gap} known gaps, {n_skip} untested")
    # Known gaps and untested features are expected; only real mismatches fail.
    return 1 if n_fail else 0


if __name__ == "__main__":
    sys.exit(main())
