"""Read every table with DuckDB and compare against Spark's measured answers.

Expected values come from truth.json, which build.py produced by running the
same SQL through Spark. Nothing in this file is a hardcoded constant from a
previous run, including the snapshot IDs used for time travel.
"""
import json
import os
import statistics
import sys
import time

import duckdb

from spark_setup import metadata_json, TRUTH_PATH, WAREHOUSE
import checks as C

PASS, FAIL, SKIP, GAP = "PASS", "FAIL", "n/a ", "GAP "
results = []


def record(label, status, detail=""):
    """GAP = a known, expected limitation -- reported, but not a suite failure."""
    results.append((label, status, detail))
    icon = {"PASS": "✓", "FAIL": "✗", SKIP: "-", GAP: "!"}[status]
    print(f"  {icon} {label:44} {status}  {detail}", flush=True)


def scan(table):
    return f"iceberg_scan('{metadata_json(table)}')"


def main():
    if not os.path.exists(TRUTH_PATH):
        print(f"missing {TRUTH_PATH} -- run: python bench/build.py", file=sys.stderr)
        return 2
    truth = json.load(open(TRUTH_PATH))

    con = duckdb.connect()
    con.execute("INSTALL iceberg; LOAD iceberg;")
    print(f"\nDuckDB {duckdb.__version__}  vs  Spark {truth['versions']['spark']} "
          f"+ Iceberg {truth['versions']['iceberg']}\n")

    print("READ CORRECTNESS (DuckDB result vs Spark result on identical SQL)")
    for key, table, label, sql in C.CHECKS:
        exp = [tuple(r) for r in truth["checks"][key]["rows"]]
        try:
            got = C.normalize_rows(con.execute(sql.format(t=scan(table))).fetchall())
        except Exception as e:
            record(label, FAIL, f"ERROR {type(e).__name__}: {str(e).splitlines()[0][:70]}")
            continue
        record(label, PASS if got == exp else FAIL,
               "" if got == exp else f"duckdb={got} spark={exp}")

    # Row lineage metadata columns
    exp = [tuple(r) for r in truth["lineage"]]
    try:
        got = C.normalize_rows(con.execute(
            C.LINEAGE_SQL.format(t=scan("f.lineage"), cols=", ".join(C.LINEAGE_COLS))
        ).fetchall())
        record("v3 row lineage (_row_id + _last_updated_seq)", PASS if got == exp else FAIL,
               "" if got == exp else f"duckdb={got} spark={exp}")
    except Exception as e:
        record("v3 row lineage (_row_id + _last_updated_seq)", FAIL,
               f"ERROR {str(e).splitlines()[0][:70]}")

    # Variant, compared as parsed JSON so key order and number formatting differences
    # between the two engines do not create false failures.
    exp = [[r[0], r[1]] for r in truth["variant"]]
    try:
        raw = con.execute(C.VARIANT_SQL_DUCKDB.format(t=scan(C.VARIANT_TABLE))).fetchall()
        got = [[r[0], C.normalize_json(r[1])] for r in raw]
        record("v3 variant type (deep/awkward values)", PASS if got == exp else FAIL,
               "" if got == exp else f"duckdb={got} spark={exp}")
        vtype = con.execute(f"SELECT typeof(v) FROM {scan(C.VARIANT_TABLE)} LIMIT 1").fetchone()[0]
        record("v3 variant exposed as native type", PASS if vtype.upper() == "VARIANT" else FAIL,
               f"typeof() = {vtype}")
    except Exception as e:
        record("v3 variant type (deep/awkward values)", FAIL,
               f"ERROR {str(e).splitlines()[0][:70]}")

    # Time travel: snapshot IDs come from truth.json, generated by this clone's
    # build. Compare value-sensitive aggregates and an ordered sample, not just
    # row count -- a reader can return the right NUMBER of wrong rows.
    ok, detail = 0, ""
    for entry in truth["timetravel"]:
        sid = entry["snapshot_id"]
        src = f"iceberg_scan('{metadata_json('h.part')}', snapshot_from_id={sid})"
        try:
            agg = C.normalize_row(con.execute(
                f"SELECT count(*), sum(id), round(sum(amount),2) FROM {src}").fetchone())
            sample = C.normalize_rows(con.execute(
                f"SELECT id, cat, amount FROM {src} ORDER BY id LIMIT 5").fetchall())
            exp_agg = C.normalize_row((entry["count"], entry["sum_id"], entry["sum_amount"]))
            exp_sample = [tuple(r) for r in entry["sample"]]
            if agg == exp_agg and sample == exp_sample:
                ok += 1
            elif not detail:
                detail = (f"snapshot {sid}: duckdb agg={agg} spark={exp_agg}"
                          if agg != exp_agg else f"snapshot {sid}: sample rows differ")
        except Exception as e:
            if not detail:
                detail = f"snapshot {sid}: {type(e).__name__}: {str(e).splitlines()[0][:60]}"
    n_tt = len(truth["timetravel"])
    record("v3 time travel across DV snapshots", PASS if ok == n_tt else FAIL,
           f"{ok}/{n_tt} snapshots match (count+sum_id+sum_amount+sample)" + (f" | {detail}" if detail else ""))

    # ---- v3 artifact validation ----
    # The read checks above would still pass if the writer silently fell back to
    # v2 positional deletes, so assert the on-disk representation explicitly.
    print("\nV3 ARTIFACT VALIDATION (what the writer actually produced)")
    v3, v2 = truth["layout"]["v3"], truth["layout"]["v2"]
    record("v3 table is really format-version 3", PASS if v3["format_version"] == 3 else FAIL,
           f"format-version={v3['format_version']}")
    record("v3 deletes are Puffin deletion vectors",
           PASS if v3["puffin"] > 0 and v3["parquet_deletes"] == 0 else FAIL,
           f"{v3['puffin']} puffin, {v3['parquet_deletes']} parquet ({v3['delete_suffix']})")
    record("v2 baseline is really format-version 2", PASS if v2["format_version"] == 2 else FAIL,
           f"format-version={v2['format_version']}")
    record("v2 deletes are positional delete files",
           PASS if v2["parquet_deletes"] > 0 and v2["puffin"] == 0 else FAIL,
           f"{v2['puffin']} puffin, {v2['parquet_deletes']} parquet ({v2['delete_suffix']})")
    record("v3 merges DVs; v2 accumulates delete files",
           PASS if v3["delete_artifacts"] < v2["delete_artifacts"] else FAIL,
           f"v3={v3['delete_artifacts']} vs v2={v2['delete_artifacts']} artifacts "
           f"for the same 3 delete rounds")

    # ---- write side: COPY TO against a local directory ----
    # Every claim the README makes about the local write path is exercised here.
    # The catalog-based write path (ATTACH -> INSERT/UPDATE/DELETE, which does
    # produce real deletion vectors) needs a running REST catalog and is NOT
    # covered by this suite -- see README "Manual findings".
    print("\nLOCAL WRITE PATH: COPY TO (DuckDB)")
    import glob as _glob

    def fresh(name):
        d = os.path.join(WAREHOUSE, f"_dw_{name}")
        os.system(f"rm -rf '{d}'")
        return d

    def fmt_version(d):
        m = _glob.glob(os.path.join(d, "metadata", "*.metadata.json"))
        if not m:
            return None
        return json.load(open(max(m, key=os.path.getmtime)))["format-version"]

    def rows(d):
        m = _glob.glob(os.path.join(d, "metadata", "*.metadata.json"))
        return con.execute(
            f"SELECT count(*) FROM iceberg_scan('{max(m, key=os.path.getmtime)}')").fetchone()[0]

    # 1. FORMAT_VERSION 3 is requested but not honoured
    d = fresh("fv")
    try:
        con.execute(f"COPY (SELECT 1 a) TO '{d}' (FORMAT ICEBERG, FORMAT_VERSION 3)")
        fv = fmt_version(d)
        record("COPY TO honours FORMAT_VERSION 3", GAP if fv != 3 else PASS,
               f"asked for v3, got format-version={fv} (no error raised)")
    except Exception as e:
        record("COPY TO honours FORMAT_VERSION 3", GAP, f"{type(e).__name__}: {e}")

    # 2. Unknown options are not rejected
    d = fresh("opt")
    try:
        con.execute(f"COPY (SELECT 1 a) TO '{d}' (FORMAT ICEBERG, BANANA true)")
        record("COPY TO rejects unknown options", GAP,
               "'BANANA true' accepted silently -- option list is not validated")
    except Exception as e:
        record("COPY TO rejects unknown options", PASS,
               f"rejected: {str(e).splitlines()[0][:60]}")

    # 3. APPEND true does not append -- it replaces the table
    d = fresh("app")
    try:
        con.execute(f"COPY (SELECT i AS id FROM range(5) t(i)) TO '{d}' (FORMAT ICEBERG)")
        before = rows(d)
        con.execute(f"COPY (SELECT 99 AS id) TO '{d}' (FORMAT ICEBERG, APPEND true)")
        after = rows(d)
        record("COPY TO ... APPEND true appends", PASS if after == before + 1 else GAP,
               f"{before} rows + 1 appended -> {after} rows"
               + ("" if after == before + 1 else "  (table was REPLACED, prior rows lost)"))
    except Exception as e:
        record("COPY TO ... APPEND true appends", GAP, f"{type(e).__name__}: {e}")

    # 4. PARTITION_BY is ignored
    d = fresh("part")
    try:
        con.execute(f"COPY (SELECT i AS id, i%3 AS p FROM range(9) t(i)) TO '{d}' "
                    f"(FORMAT ICEBERG, PARTITION_BY p)")
        m = _glob.glob(os.path.join(d, "metadata", "*.metadata.json"))
        specs = json.load(open(max(m, key=os.path.getmtime)))["partition-specs"][0]["fields"]
        record("COPY TO ... PARTITION_BY partitions", PASS if specs else GAP,
               f"partition-spec fields = {specs}" + ("" if specs else "  (ignored)"))
    except Exception as e:
        record("COPY TO ... PARTITION_BY partitions", GAP, f"{type(e).__name__}: {e}")

    # 5. No local/hadoop catalog for ATTACH
    try:
        con.execute(f"ATTACH '{WAREHOUSE}' AS _local (TYPE ICEBERG, ENDPOINT_TYPE 'HADOOP')")
        record("ATTACH supports a local (hadoop) catalog", PASS)
        con.execute("DETACH _local")
    except Exception as e:
        record("ATTACH supports a local (hadoop) catalog", GAP,
               str(e).splitlines()[0][:92])
    os.system(f"rm -rf '{os.path.join(WAREHOUSE, '_dw_')}'*")

    # ---- features no available writer can produce ----
    print("\nUNTESTED (Spark could not write these, so DuckDB is not graded on them)")
    for feat, info in truth["unwritable"].items():
        if info["writable"]:
            record(f"{feat} (now writable!)", GAP,
                   "writer gained support -- add a DuckDB read check for this")
        else:
            record(feat, SKIP, (info["error"] or "")[:92])

    # ---- performance ----
    nrows = truth["versions"]["rows_perf_table"]
    print(f"\nREAD PERFORMANCE ({nrows:,}-row tables, same delete workload)")

    def bench(table, n=7):
        src = scan(table)
        con.execute(f"SELECT count(*) FROM {src}").fetchall()  # warm
        ts = []
        for _ in range(n):
            t0 = time.perf_counter()
            con.execute(f"SELECT count(*), sum(id) FROM {src}").fetchall()
            ts.append((time.perf_counter() - t0) * 1000)
        return statistics.median(ts)

    v3ms, v2ms = bench("p.big3"), bench("p.big2")
    lay = truth["layout"]
    print(f"  v3 deletion vectors (Puffin)   median {v3ms:7.1f} ms   "
          f"{lay['v3']['delete_artifacts']} delete artifacts, "
          f"{lay['v3']['delete_bytes']/1024:.1f} KiB")
    print(f"  v2 positional deletes          median {v2ms:7.1f} ms   "
          f"{lay['v2']['delete_artifacts']} delete artifacts, "
          f"{lay['v2']['delete_bytes']/1024:.1f} KiB")
    print(f"  -> v3 is {v2ms/v3ms:.1f}x faster on this machine")

    # ---- summary ----
    n_fail = sum(1 for _, s, _ in results if s == FAIL)
    n_pass = sum(1 for _, s, _ in results if s == PASS)
    n_skip = sum(1 for _, s, _ in results if s == SKIP)
    n_gap = sum(1 for _, s, _ in results if s == GAP)
    print(f"\n{n_pass} passed, {n_fail} failed, {n_gap} known gaps, {n_skip} untested")
    # Known gaps and untested features are expected; only real mismatches fail.
    return 1 if n_fail else 0


if __name__ == "__main__":
    sys.exit(main())
